#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=4:00:00,vmem=50gb
#PBS -M 
#PBS -m e
#PBS -Pubmed_Data_Download
#PBS -j oe

cd /N/dc2/projects/MAMMALEXP/
mkdir PubMed
cd ./PubMed
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0001.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0002.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0003.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0004.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0005.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0006.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0007.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0008.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0009.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0010.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0011.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0012.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0013.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0014.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0015.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0016.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0017.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0018.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0019.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0020.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0021.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0022.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0023.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0024.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0025.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0026.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0027.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0028.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0029.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0030.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0031.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0032.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0033.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0034.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0035.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0036.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0037.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0038.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0039.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0040.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0041.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0042.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0043.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0044.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0045.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0046.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0047.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0048.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0049.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0050.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0051.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0052.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0053.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0054.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0055.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0056.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0057.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0058.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0059.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0060.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0061.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0062.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0063.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0064.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0065.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0066.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0067.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0068.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0069.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0070.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0071.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0072.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0073.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0074.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0075.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0076.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0077.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0078.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0079.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0080.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0081.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0082.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0083.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0084.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0085.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0086.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0087.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0088.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0089.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0090.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0091.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0092.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0093.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0094.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0095.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0096.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0097.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0098.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0099.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0100.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0101.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0102.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0103.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0104.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0105.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0106.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0107.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0108.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0109.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0110.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0111.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0112.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0113.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0114.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0115.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0116.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0117.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0118.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0119.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0120.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0121.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0122.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0123.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0124.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0125.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0126.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0127.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0128.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0129.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0130.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0131.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0132.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0133.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0134.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0135.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0136.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0137.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0138.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0139.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0140.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0141.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0142.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0143.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0144.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0145.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0146.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0147.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0148.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0149.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0150.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0151.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0152.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0153.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0154.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0155.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0156.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0157.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0158.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0159.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0160.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0161.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0162.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0163.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0164.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0165.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0166.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0167.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0168.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0169.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0170.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0171.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0172.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0173.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0174.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0175.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0176.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0177.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0178.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0179.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0180.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0181.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0182.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0183.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0184.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0185.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0186.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0187.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0188.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0189.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0190.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0191.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0192.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0193.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0194.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0195.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0196.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0197.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0198.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0199.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0200.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0201.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0202.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0203.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0204.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0205.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0206.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0207.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0208.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0209.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0210.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0211.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0212.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0213.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0214.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0215.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0216.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0217.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0218.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0219.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0220.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0221.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0222.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0223.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0224.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0225.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0226.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0227.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0228.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0229.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0230.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0231.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0232.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0233.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0234.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0235.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0236.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0237.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0238.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0239.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0240.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0241.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0242.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0243.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0244.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0245.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0246.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0247.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0248.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0249.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0250.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0251.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0252.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0253.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0254.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0255.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0256.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0257.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0258.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0259.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0260.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0261.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0262.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0263.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0264.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0265.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0266.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0267.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0268.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0269.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0270.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0271.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0272.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0273.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0274.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0275.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0276.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0277.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0278.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0279.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0280.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0281.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0282.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0283.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0284.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0285.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0286.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0287.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0288.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0289.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0290.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0291.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0292.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0293.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0294.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0295.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0296.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0297.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0298.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0299.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0300.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0301.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0302.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0303.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0304.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0305.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0306.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0307.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0308.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0309.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0310.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0311.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0312.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0313.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0314.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0315.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0316.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0317.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0318.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0319.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0320.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0321.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0322.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0323.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0324.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0325.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0326.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0327.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0328.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0329.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0330.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0331.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0332.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0333.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0334.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0335.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0336.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0337.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0338.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0339.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0340.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0341.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0342.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0343.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0344.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0345.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0346.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0347.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0348.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0349.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0350.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0351.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0352.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0353.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0354.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0355.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0356.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0357.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0358.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0359.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0360.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0361.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0362.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0363.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0364.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0365.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0366.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0367.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0368.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0369.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0370.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0371.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0372.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0373.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0374.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0375.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0376.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0377.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0378.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0379.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0380.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0381.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0382.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0383.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0384.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0385.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0386.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0387.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0388.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0389.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0390.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0391.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0392.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0393.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0394.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0395.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0396.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0397.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0398.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0399.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0400.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0401.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0402.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0403.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0404.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0405.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0406.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0407.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0408.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0409.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0410.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0411.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0412.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0413.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0414.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0415.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0416.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0417.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0418.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0419.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0420.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0421.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0422.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0423.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0424.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0425.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0426.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0427.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0428.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0429.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0430.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0431.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0432.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0433.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0434.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0435.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0436.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0437.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0438.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0439.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0440.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0441.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0442.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0443.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0444.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0445.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0446.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0447.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0448.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0449.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0450.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0451.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0452.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0453.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0454.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0455.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0456.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0457.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0458.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0459.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0460.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0461.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0462.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0463.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0464.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0465.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0466.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0467.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0468.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0469.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0470.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0471.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0472.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0473.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0474.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0475.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0476.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0477.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0478.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0479.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0480.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0481.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0482.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0483.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0484.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0485.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0486.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0487.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0488.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0489.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0490.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0491.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0492.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0493.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0494.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0495.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0496.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0497.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0498.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0499.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0500.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0501.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0502.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0503.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0504.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0505.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0506.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0507.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0508.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0509.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0510.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0511.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0512.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0513.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0514.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0515.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0516.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0517.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0518.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0519.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0520.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0521.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0522.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0523.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0524.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0525.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0526.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0527.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0528.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0529.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0530.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0531.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0532.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0533.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0534.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0535.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0536.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0537.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0538.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0539.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0540.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0541.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0542.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0543.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0544.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0545.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0546.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0547.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0548.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0549.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0550.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0551.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0552.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0553.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0554.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0555.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0556.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0557.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0558.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0559.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0560.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0561.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0562.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0563.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0564.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0565.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0566.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0567.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0568.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0569.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0570.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0571.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0572.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0573.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0574.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0575.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0576.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0577.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0578.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0579.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0580.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0581.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0582.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0583.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0584.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0585.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0586.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0587.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0588.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0589.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0590.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0591.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0592.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0593.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0594.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0595.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0596.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0597.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0598.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0599.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0600.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0601.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0602.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0603.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0604.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0605.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0606.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0607.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0608.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0609.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0610.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0611.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0612.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0613.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0614.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0615.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0616.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0617.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0618.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0619.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0620.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0621.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0622.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0623.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0624.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0625.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0626.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0627.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0628.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0629.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0630.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0631.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0632.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0633.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0634.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0635.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0636.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0637.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0638.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0639.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0640.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0641.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0642.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0643.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0644.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0645.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0646.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0647.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0648.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0649.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0650.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0651.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0652.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0653.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0654.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0655.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0656.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0657.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0658.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0659.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0660.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0661.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0662.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0663.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0664.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0665.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0666.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0667.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0668.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0669.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0670.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0671.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0672.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0673.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0674.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0675.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0676.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0677.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0678.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0679.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0680.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0681.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0682.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0683.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0684.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0685.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0686.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0687.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0688.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0689.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0690.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0691.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0692.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0693.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0694.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0695.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0696.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0697.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0698.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0699.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0700.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0701.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0702.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0703.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0704.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0705.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0706.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0707.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0708.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0709.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0710.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0711.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0712.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0713.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0714.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0715.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0716.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0717.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0718.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0719.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0720.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0721.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0722.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0723.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0724.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0725.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0726.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0727.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0728.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0729.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0730.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0731.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0732.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0733.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0734.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0735.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0736.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0737.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0738.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0739.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0740.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0741.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0742.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0743.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0744.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0745.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0746.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0747.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0748.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0749.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0750.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0751.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0752.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0753.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0754.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0755.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0756.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0757.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0758.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0759.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0760.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0761.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0762.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0763.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0764.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0765.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0766.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0767.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0768.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0769.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0770.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0771.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0772.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0773.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0774.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0775.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0776.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0777.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0778.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0779.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0780.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0781.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0782.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0783.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0784.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0785.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0786.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0787.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0788.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0789.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0790.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0791.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0792.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0793.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0794.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0795.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0796.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0797.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0798.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0799.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0800.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0801.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0802.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0803.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0804.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0805.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0806.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0807.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0808.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0809.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0810.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0811.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0812.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0813.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0814.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0815.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0816.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0817.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0818.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0819.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0820.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0821.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0822.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0823.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0824.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0825.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0826.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0827.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0828.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0829.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0830.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0831.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0832.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0833.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0834.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0835.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0836.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0837.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0838.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0839.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0840.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0841.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0842.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0843.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0844.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0845.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0846.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0847.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0848.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0849.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0850.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0851.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0852.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0853.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0854.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0855.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0856.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0857.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0858.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0859.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0860.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0861.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0862.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0863.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0864.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0865.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0866.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0867.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0868.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0869.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0870.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0871.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0872.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0873.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0874.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0875.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0876.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0877.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0878.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0879.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0880.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0881.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0882.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0883.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0884.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0885.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0886.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0887.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0888.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0889.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0890.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0891.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0892.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0893.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0894.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0895.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0896.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0897.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0898.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0899.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0900.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0901.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0902.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0903.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0904.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0905.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0906.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0907.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0908.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0909.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0910.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0911.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0912.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0913.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0914.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0915.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0916.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0917.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0918.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0919.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0920.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0921.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0922.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0923.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0924.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0925.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0926.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0927.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0928.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0929.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0930.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0931.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0932.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0933.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0934.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0935.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0936.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0937.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0938.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0939.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0940.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0941.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0942.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0943.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0944.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0945.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0946.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0947.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0948.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0949.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0950.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0951.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0952.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0953.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0954.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0955.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0956.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0957.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0958.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0959.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0960.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0961.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0962.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0963.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0964.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0965.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0966.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0967.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0968.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0969.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0970.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0971.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0972.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0973.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0974.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0975.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0976.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0977.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0978.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0979.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0980.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0981.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0982.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0983.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0984.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0985.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0986.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0987.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0988.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0989.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0990.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0991.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0992.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0993.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0994.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0995.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0996.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0997.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0998.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n0999.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1000.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1001.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1002.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1003.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1004.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1005.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1006.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1007.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1008.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1009.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1010.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1011.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1012.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1013.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1014.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed20n1015.xml.gz
gunzip pubmed20n*.gz
